build:
  stage: build
  image: trzeci/emscripten
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
  - apt-get update
  - apt-get -y --no-install-recommends install python3
  - apt-get -y --no-install-recommends install python3-pip
  - pip3 install -U sphinx
  - cmake .
  - emmake make
  - emmake make docs
  - mkdir ci-build
  - cp -r bin/* ci-build
  artifacts:
    paths:
      - ci-build/

tests:
  stage: test
  image: nnaumenko/emscripten-firefox
  script:
  # list browsers, for reference only 
  - emrun --list_browsers
  # run tests with Firefox (will return exit code 1 if test failed)
  - emrun --browser firefox ci-build/test/main.html --gtest_output="xml:test.xml" >ci-build/test/firefox_test_output.txt
  # make bin/test/test.xml
  - sed -n '/<<<<\/test.xml:BEGIN>>>>/,/<<<<\/test.xml:END>>>>/{ /<<<<\/test.xml:BEGIN>>>>/d; /<<<<\/test.xml:END>>>>/d; p }' ci-build/test/firefox_test_output.txt >ci-build/test/test.xml
  # additionally check for failure reports in ci-build/test/test.xml
  - test -f ci-build/test/test.xml
  - if [ "$(grep 'failures="[1-9]' ci-build/test/test.xml)" != "" ]; then exit 1; fi
  artifacts:
    paths:
      - ci-build/    
    reports:
      junit: ci-build/test/test.xml
 
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r ci-build/* public
    - cp pages/* public
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master