build:
  stage: build
  image: trzeci/emscripten
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
  - emmake make all
  - mkdir ci-build
  - cp -r bin/* ci-build
  artifacts:
    paths:
      - ci-build/

tests:
  stage: test
  script:
  - echo TODO
  dependencies:
    - build
  artifacts:
    reports:
      junit: bin/test/test.xml

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r ci-build/* public
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master