build:
  stage: build
  image: trzeci/emscripten
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
  - cmake .
  - emmake make
  - mkdir ci-build
  - cp -r bin/* ci-build
  artifacts:
    paths:
      - ci-build

docs:
  stage: build
  image: python:3.8.0b1-alpine3.10
  script:
  - apk update
  - apk add cmake
  # python3 -m pip install --upgrade pip
  - pip3 install -U sphinx
  - mkdir doctemp
  - mkdir ci-build
  - sphinx-build -d ./doctemp ./docs/sphinx ./ci-build/docs
  artifacts:
    paths:
      - ci-build

tests:
  stage: test
  image: nnaumenko/emscripten-firefox
  script:
  # list browsers, for reference only 
  - emrun --list_browsers
  # run tests with Firefox (will return exit code 1 if test failed)
  - emrun --browser firefox ci-build/test/main.html --gtest_output="xml:test.xml" >ci-build/test/firefox_test_output.txt
  # make bin/test/test.xml
  - sed -n '/<<<<\/test.xml:BEGIN>>>>/,/<<<<\/test.xml:END>>>>/{ /<<<<\/test.xml:BEGIN>>>>/d; /<<<<\/test.xml:END>>>>/d; p }' ci-build/test/firefox_test_output.txt >ci-build/test/test.xml
  # possible to additionally check for failure reports in ci-build/test/test.xml
  # test -f ci-build/test/test.xml
  # if [ "$(grep 'failures="[1-9]' ci-build/test/test.xml)" != "" ]; then exit 1; fi
  artifacts:
    paths:
      - ci-build
    reports:
      junit: ci-build/test/test.xml
 
pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r ci-build/* public
    - cp pages/* public
  dependencies:
    - build
    - tests
  artifacts:
    paths:
      - public
  only:
    - master

codecov:
  stage: deploy
  image: ubuntu:18.04
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install xz-utils build-essential curl cmake ca-certificates git
    - curl -SL http://releases.llvm.org/8.0.0/clang%2bllvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04.tar.xz | tar -xJC .
    - mv clang+llvm-8.0.0-x86_64-linux-gnu-ubuntu-18.04 /clang-8.0.0
    - export PATH=/clang-8.0.0/bin:$PATH
    - export LD_LIBRARY_PATH=/clang-8.0.0/lib:$LD_LIBRARY_PATH
    - cd test/coverage
    - cmake .
    - make
    - ../../bin/test/testcov
    - llvm-profdata merge -sparse default.profraw -o default.profdata
    - llvm-profdata show -all-functions -counts -ic-targets default.profdata > profile.txt
    - llvm-cov show ../../bin/test/testcov -instr-profile=default.profdata >coverage.txt
    - mkdir ../../ci-profile-coverage
    - cp {default.*,profile.txt,coverage.txt} ../../ci-profile-coverage
    - curl -S https://codecov.io/bash -o codecov.sh
    - chmod +x codecov.sh
    - ./codecov.sh
  artifacts:
    paths:
      - ci-profile-coverage
  only:
    - master