build:
  stage: build
  image: trzeci/emscripten
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
  - apt-get update
  - apt-get -y install python3
  - apt-get -y install python3-pip
  - pip3 install -U sphinx
  - cmake .
  - emmake make
  - emmake make docs
  - mkdir ci-build
  - cp -r bin/* ci-build
  artifacts:
    paths:
      - ci-build/

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r ci-build/* public
    - cp pages/* public
  dependencies:
    - build
  artifacts:
    paths:
      - public
  only:
    - master