pages:
  stage: test
  script:
  - 
  artifacts:
    reports:
      junit: bin/test/test.xml
      
  stage: deploy
  script:
    - mkdir public
    - cp -r bin/* public
  artifacts:
    paths:
      - public
  only:
    - master